name: RedShot
version: "1.0"
main: navy.warspite.minecraft.redshot.Main
api-version: "1.16"
author: warspite1126
commands:
  redshot:
    usage: "/<command>"
    description: "RedShots Command"
    aliases:
      - rshot